train_dataset: hdmapnet
# dataroot: ${DATA_ROOT}/nuscenes
dataroot: /home/user/data/Dataset/nuscenes/v1.0-trainval
nuscenes_version: v1.0-trainval
label_root: nuscenes/hdmapnet
img_size: [800, 600]
num_class: 3
# 'contour', 'ped_crossing', 'road_divider', 'lane_divider'
class_weights:
  -    1.0    # road_divider, lane_divider -> line_classes
  -    1.0    # ped_crossing
  -    1.0    # road_segment, lane -> contour
  # -    1.0    # lane_divider
  # -    1.7    # road_segment
  # -    5.9    # lane
  # -    3.3    # ped_crossing
  # -    7.7    # stop_line ### added
  # -    4.6    # road_divider
  # -    4.3    # lane_divider ### added
  # -    4.3    # lane_divider ### added
  # -    8.0    # car
  # -   10.3    # truck
  # -   10.6    # bus
  # -    6.9    # trailer
  # -   11.8    # construction_vehicle
  # -   30.1    # pedestrian
  # -   33.6    # motorcycle
  # -   41.2    # bicycle
  # -   44.3    # traffic_cone
  # -   15.9    # barrier

# Prior probability of a positive prediction, used to initialise classifier
prior: 
  - 0.14491   # road_divider, lane_divider -> line_classes
  - 0.02407   # ped_crossing
  - 0.44679   # road_segment, lane -> contour
  # - 0.12987   # stop_line ### added
  # - 0.02994   # carpark_area
  # - 0.02694   # road_divider ### added
  # - 0.03124   # lane_divider ### added
  # - 0.02086   # car
  # - 0.00477   # truck
  # - 0.00156   # bus
  # - 0.00189   # trailer
  # - 0.00084   # construction_vehicle
  # - 0.00119   # pedestrian
  # - 0.00019   # motorcycle
  # - 0.00012   # bicycle
  # - 0.00031   # traffic_cone
  # - 0.00176   # barrier

ved:
  bottleneck_dim: 18

vpn:
  output_size : [29, 50]